/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import SQLServerProvider.SQLServerProvider;
import com.DAO.NhanVienDAO;
import com.DTO.ChucVuDTO;
import com.DTO.NhanVienDTO;
import com.java.loadChucVu;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javaswingdev.message.MessageDialog;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.ResultSet;
import java.util.ArrayList;
/**
 *
 * @author ACER
 */
public class Form_ThemNhanVien extends javax.swing.JPanel {
    String duongDanAnh = "src\\img\\Customer.png";
    private Form_QuanLyNhanVien formQuanLyNhanVien;
    private Main main;
    SQLServerProvider conn = new SQLServerProvider();
    /**
     * Creates new form Form_ThemNhanVien
     */
    public Form_ThemNhanVien(Form_QuanLyNhanVien formQuanLyNhanVien,Main main) {
        this.formQuanLyNhanVien = formQuanLyNhanVien;
        this.main = main;
        conn.open();
        initComponents();
        loadCboCV();
        txtMaNV.setText("NV"+(khoaChinhTuDong()+1));
        conn.close();
    }

    private void loadCboCV()
    {  
        loadChucVu load = new loadChucVu();
        List<ChucVuDTO> list = load.getData();
        cboChucVu.removeAllItems();
        list.forEach(o -> {
            cboChucVu.addItem(o);
        });
    }
    
    public int khoaChinhTuDong()
    {
        int count = 0;
        try {
            String sql = "SELECT COUNT(*) as count FROM NHANVIEN";
            ResultSet rs = conn.executeQuery(sql);
            while(rs.next())
                count = rs.getInt("count");
        } catch (Exception e) {
        }
        return count;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new textfield.TextField();
        txtMaNV = new textfield.TextField();
        txtTenNV = new textfield.TextField();
        txtDiaChiNV = new textfield.TextField();
        txtSoDT = new textfield.TextField();
        cboChucVu = new combobox.Combobox<>();
        btnThemChucVu = new com.raven.component.Button();
        btnHuy = new com.raven.component.Button();
        btnThemNV = new com.raven.component.Button();
        btnThemAnh = new com.raven.component.Button();

        lblAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Customer.png"))); // NOI18N
        lblAnh.setToolTipText("");
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("THÊM NHÂN VIÊN MỚI");

        txtEmail.setLabelText("Nhập Email");

        txtMaNV.setEnabled(false);
        txtMaNV.setLabelText("Nhập nhân viên");

        txtTenNV.setLabelText("Nhập tên nhân viên");

        txtDiaChiNV.setLabelText("Nhập địa chỉ");

        txtSoDT.setLabelText("Nhập số điện thoại");

        cboChucVu.setLabeText("Chọn chức vụ");

        btnThemChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add.png"))); // NOI18N
        btnThemChucVu.setShadowColor(new java.awt.Color(102, 102, 255));

        btnHuy.setBackground(new java.awt.Color(244, 67, 54));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cancel.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setIconTextGap(15);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThemNV.setBackground(new java.awt.Color(76, 175, 80));
        btnThemNV.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/addWhite.png"))); // NOI18N
        btnThemNV.setText("Thêm nhân viên");
        btnThemNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemNV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemNV.setIconTextGap(15);
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnThemAnh.setBackground(new java.awt.Color(102, 153, 255));
        btnThemAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/addWhite.png"))); // NOI18N
        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemAnh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemAnh.setIconTextGap(15);
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtDiaChiNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThemChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThemChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed

        MessageDialog obj = new MessageDialog(main);

        obj.showMessage("Bạn chắc chắn muốn thoát ?", "Tất cả dữ liệu đã nhập sẽ mất");
        if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            SwingUtilities.getWindowAncestor(this).dispose();
        } else {
            System.out.println("User clicked Cancel");
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed

        if (txtMaNV.getText().isEmpty() || txtTenNV.getText().isEmpty() || txtSoDT.getText().isEmpty() || txtEmail.getText().isEmpty() || txtDiaChiNV.getText().isEmpty() || cboChucVu.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin nhân viên.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String email = txtEmail.getText();
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ email hợp lệ.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }


        // Tiến hành thêm sách vào cơ sở dữ liệu với các thông tin đã kiểm tra
        NhanVienDTO nv = new NhanVienDTO();
        nv.setMaNV(txtMaNV.getText());
        nv.setHoTenNV(txtTenNV.getText());
        nv.setDiaChiNV(txtDiaChiNV.getText());
        nv.setEmailNV(txtEmail.getText());
        nv.setSoDT(txtSoDT.getText());
        ChucVuDTO cv = (ChucVuDTO) cboChucVu.getSelectedItem();
        nv.setMaCV(cv.getMaCV());
        nv.setAnhNV(duongDanAnh);
        nv.setTrangThai(1);
        boolean kq = NhanVienDAO.themNhanVien(nv);
        if(kq)
        {
            JOptionPane.showMessageDialog(this, "Nhân viên đã được thêm thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ArrayList<NhanVienDTO> ds = NhanVienDAO.layDS();
            formQuanLyNhanVien.capNhatDuLieuBang(ds);
            //            SwingUtilities.getWindowAncestor(this).dispose();
        }
        else
        JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại.", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        try {
            JFileChooser f = new JFileChooser("D:\\QuanLyNhaSach\\src\\img");
            f.setDialogTitle("Mở File");
            f.showOpenDialog(null);
            File ftenAnh = f.getSelectedFile();
            duongDanAnh = ftenAnh.getAbsolutePath();
            if(duongDanAnh != null)
            {
                lblAnh.setIcon(ResizeImage(String.valueOf(duongDanAnh)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chưa chọn ảnh");
        }

    }//GEN-LAST:event_btnThemAnhActionPerformed

    private Icon ResizeImage(String imagePath) {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email.matches(emailRegex);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnHuy;
    private com.raven.component.Button btnThemAnh;
    private com.raven.component.Button btnThemChucVu;
    private com.raven.component.Button btnThemNV;
    private combobox.Combobox<Object> cboChucVu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnh;
    private textfield.TextField txtDiaChiNV;
    private textfield.TextField txtEmail;
    private textfield.TextField txtMaNV;
    private textfield.TextField txtSoDT;
    private textfield.TextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
