/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import SQLServerProvider.SQLServerProvider;
import com.DAO.KhuyenMaiDAO;
import com.DAO.XuLyHoaDonDAO;
import com.DTO.KhachHangDTO;
import com.DTO.KhuyenMaiDTO;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER NITRO5
 */
public class Form_TaoKhuyenMai extends javax.swing.JPanel {

    private Main main;
    SQLServerProvider conn = new SQLServerProvider();
    /**
     * Creates new form Form_TaoKhuyenMai
     */
    public Form_TaoKhuyenMai(Main main) {
        this.main = main;
        initComponents();
        conn.open();
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
        tblKhuyenMai.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                displaySelectedRow();
            }
        }});
        loadtblKhuyenMai();
        conn.close();
    }
    public void displaySelectedRow() {
        int selectedRow = tblKhuyenMai.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy giá trị từ các cột của dòng được chọn
            String maKM = (String) tblKhuyenMai.getValueAt(selectedRow, 0);
            String tenKM = (String) tblKhuyenMai.getValueAt(selectedRow, 1);
            String ngayBD = (String) tblKhuyenMai.getValueAt(selectedRow, 2);
            String ngayKT = (String) tblKhuyenMai.getValueAt(selectedRow, 3);
            double khuyenMai = Double.parseDouble(tblKhuyenMai.getValueAt(selectedRow, 4).toString());
            
            txtMaKM.setText(maKM);
            txtTenKhuyenMai.setText(tenKM);
            txtNgayBD.setText(ngayBD);
            txtNgayKT.setText(ngayKT);
            txtGiamGia.setText(String.valueOf(khuyenMai));
        }
    }
    public void loadtblKhuyenMai()
    {
        conn.open();
        String sql = "Select * FROM KHUYENMAI";
        ResultSet rs = conn.executeQuery(sql);
        DefaultTableModel model = (DefaultTableModel) this.tblKhuyenMai.getModel();
        model.setRowCount(0);
        try {
            while(rs.next()) {
                String maKM = String.valueOf(rs.getString("MAKM"));
                String tenKM = String.valueOf(rs.getString("TENKM"));
                String ngayBD = String.valueOf(rs.getString("NGAYBD"));
                String ngayKT = String.valueOf(rs.getString("NGAYKT"));
                double khuyenMai = Double.parseDouble(rs.getString("GIAMGIA"));
                Object[] rowData = {maKM,tenKM,ngayBD,ngayKT,khuyenMai};
                    model.addRow(rowData);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        dateChooser1 = new com.raven.datechooser.DateChooser();
        panelShadow2 = new com.raven.swing.PanelShadow();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtNgayKT = new com.raven.component.TextField();
        jLabel11 = new javax.swing.JLabel();
        btnSuaKM = new com.raven.component.Button();
        txtTenKhuyenMai = new com.raven.component.TextField();
        txtGiamGia = new com.raven.component.TextField();
        btnThemKM = new com.raven.component.Button();
        btnXoaKM = new com.raven.component.Button();
        jLabel12 = new javax.swing.JLabel();
        txtMaKM = new com.raven.component.TextField();
        txtNgayBD = new com.raven.component.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new com.raven.component.Table();

        dateChooser.setDateFormat("yyyy-MM-dd");
        dateChooser.setInheritsPopupMenu(true);
        dateChooser.setTextRefernce(txtNgayBD);

        dateChooser1.setDateFormat("yyyy-MM-dd");
        dateChooser1.setTextRefernce(txtNgayKT);

        setOpaque(false);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(140, 110, 207));
        jLabel7.setText("Thông tin khuyến mãi");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã khuyến mãi");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ngày bắt đầu");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Giảm giá");

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtNgayKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayKTActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày kết thúc");

        btnSuaKM.setBackground(new java.awt.Color(0, 140, 186));
        btnSuaKM.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/edit_1.png"))); // NOI18N
        btnSuaKM.setText("Sửa KM");
        btnSuaKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaKM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSuaKM.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSuaKM.setIconTextGap(15);
        btnSuaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKMActionPerformed(evt);
            }
        });

        txtTenKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhuyenMaiActionPerformed(evt);
            }
        });

        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });

        btnThemKM.setBackground(new java.awt.Color(76, 175, 80));
        btnThemKM.setForeground(new java.awt.Color(255, 255, 255));
        btnThemKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/addWhite.png"))); // NOI18N
        btnThemKM.setText("Thêm KM");
        btnThemKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemKM.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemKM.setIconTextGap(15);
        btnThemKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKMActionPerformed(evt);
            }
        });

        btnXoaKM.setBackground(new java.awt.Color(244, 67, 54));
        btnXoaKM.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cancel.png"))); // NOI18N
        btnXoaKM.setText("Xóa KM");
        btnXoaKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaKM.setIconTextGap(15);
        btnXoaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKMActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tên khuyến mãi");

        txtMaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKMActionPerformed(evt);
            }
        });

        txtNgayBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow2Layout = new javax.swing.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThemKM, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSuaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaKM, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelShadow2Layout.createSequentialGroup()
                        .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(panelShadow2Layout.createSequentialGroup()
                        .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addContainerGap())))
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShadow2Layout.createSequentialGroup()
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelShadow2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemKM, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mãi", "Tên KM", "Ngày BD", "Ngày KT", "Giảm giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblKhuyenMai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblKhuyenMaiPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(panelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtNgayKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayKTActionPerformed

    private void btnSuaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKMActionPerformed

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date1 = dateFormat.parse(txtNgayBD.getText());
            Date date2 = dateFormat.parse(txtNgayKT.getText());

            if (date2.after(date1)) {
                KhuyenMaiDTO kh = new KhuyenMaiDTO();
                kh.setMaKM(txtMaKM.getText());
                kh.setTenKM(txtTenKhuyenMai.getText());
                Date ngayBD = dateFormat.parse(txtNgayBD.getText());
                kh.setNgayBD(ngayBD);
                Date ngayKT = dateFormat.parse(txtNgayKT.getText());
                kh.setNgayKT(ngayKT);
                kh.setGiamGia(Double.parseDouble(txtGiamGia.getText()));
                boolean kq = KhuyenMaiDAO.capNhatKhuyenMai(kh);
                if(kq)
                {
                    JOptionPane.showMessageDialog(this, "Cập nhật khuyến mãi thành công");
                    loadtblKhuyenMai();
                }
                else
                    JOptionPane.showMessageDialog(this, "Cập nhật khuyến mãi thất bại");
                
            } else {
                JOptionPane.showMessageDialog(this, "Ngày bắt đầu lớn hơn ngày kết thúc!");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Định dạng không hợp lệ");
        }
    }//GEN-LAST:event_btnSuaKMActionPerformed

    private void txtTenKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhuyenMaiActionPerformed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void btnThemKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKMActionPerformed

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date1 = dateFormat.parse(txtNgayBD.getText());
            Date date2 = dateFormat.parse(txtNgayKT.getText());

            if (date2.after(date1)) {
                KhuyenMaiDTO kh = new KhuyenMaiDTO();
                kh.setMaKM(txtMaKM.getText());
                kh.setTenKM(txtTenKhuyenMai.getText());
                Date ngayBD = dateFormat.parse(txtNgayBD.getText());
                kh.setNgayBD(ngayBD);
                Date ngayKT = dateFormat.parse(txtNgayKT.getText());
                kh.setNgayKT(ngayKT);
                kh.setGiamGia(Double.parseDouble(txtGiamGia.getText()));
                boolean kq = KhuyenMaiDAO.themKhuyenMai(kh);
                if(kq)
                {
                    JOptionPane.showMessageDialog(this, "Thêm khuyến mãi thành công");
                    loadtblKhuyenMai();
                }
                else
                    JOptionPane.showMessageDialog(this, "Thêm khuyến mãi thất bại");
                
            } else {
                JOptionPane.showMessageDialog(this, "Ngày bắt đầu lớn hơn ngày kết thúc!");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please enter the date in yyyy-MM-dd format.");
        }
    }//GEN-LAST:event_btnThemKMActionPerformed

    private void btnXoaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKMActionPerformed

        try {
            boolean kq = KhuyenMaiDAO.xoaKhuyenMai(txtMaKM.getText());
                if(kq)
                {
                    JOptionPane.showMessageDialog(this, "Xóa khuyến mãi thành công");
                    loadtblKhuyenMai();
                }
                else
                    JOptionPane.showMessageDialog(this, "Xóa khuyến mãi thất bại");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Khóa chính đang được sử dụng.");
        }
    }//GEN-LAST:event_btnXoaKMActionPerformed

    private void txtMaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKMActionPerformed

    private void tblKhuyenMaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblKhuyenMaiPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKhuyenMaiPropertyChange

    private void txtNgayBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnSuaKM;
    private com.raven.component.Button btnThemKM;
    private com.raven.component.Button btnXoaKM;
    private com.raven.datechooser.DateChooser dateChooser;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelShadow panelShadow2;
    private com.raven.component.Table tblKhuyenMai;
    private com.raven.component.TextField txtGiamGia;
    private com.raven.component.TextField txtMaKM;
    private com.raven.component.TextField txtNgayBD;
    private com.raven.component.TextField txtNgayKT;
    private com.raven.component.TextField txtTenKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
