/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import SQLServerProvider.SQLServerProvider;
import com.DAO.ChiTietPhieuNhapDAO;
import com.DAO.PhieuNhapDAO;
import com.DAO.SachDAO;
import com.DTO.ChiTietPhieuNhapDTO;
import com.DTO.NhaCungCapDTO;
import com.DTO.NhaXuatBanDTO;
import com.DTO.NhanVienDTO;
import com.DTO.PhieuNhapDTO;
import com.DTO.SachDTO;
import com.DTO.TacGiaDTO;
import com.DTO.TheLoaiDTO;
import com.java.loadNCC;
import com.java.loadNV;
import com.java.loadNXB;
import com.java.loadSach;
import com.java.loadTG;
import com.java.loaiTL;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import com.raven.dialog.Message;
import java.awt.Component;
import java.awt.Frame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaswingdev.message.MessageDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class Form_ThemPhieuNhap extends javax.swing.JPanel {
    private Main main;
    private Form_PhieuNhap formPhieuNhap;
    private SQLServerProvider conn;
    private DefaultTableModel model;
    
    /**
     * Creates new form Form_ThemPhieuNhap
     */
    public Form_ThemPhieuNhap(Form_PhieuNhap formPhieuNhap,Main main)
    {
        this.main = main;
        this.formPhieuNhap = formPhieuNhap;
        conn = new SQLServerProvider();
        conn.open();
        initComponents();
        model = (DefaultTableModel) tblSachNhap.getModel();
        
        loadCbo();
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
        conn.close();
    }

    
    private void loadCbo()
    {
        loadCboNCC();
        loadCboNV();
        loadCboSach();
    }
    
    private void loadCboNCC()
    {  
        loadNCC load = new loadNCC();
        List<NhaCungCapDTO> list = load.getData();
        cboNhaCungCap.removeAllItems();
        list.forEach(o -> {
            cboNhaCungCap.addItem(o);
        });
    }
    
    private void loadCboNV()
    {  
        loadNV load = new loadNV();
        List<NhanVienDTO> list = load.getData();
        cboNhanVien.removeAllItems();
        list.forEach(o -> {
            cboNhanVien.addItem(o);
        });
    }
    
    private void loadCboSach()
    {
        loadSach load = new loadSach();
        List<SachDTO> list = load.getData();
        cboMaSach.removeAllItems();
        list.forEach(o -> {
            cboMaSach.addItem(o);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        jLabel2 = new javax.swing.JLabel();
        panelShadow1 = new com.raven.swing.PanelShadow();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboMaSach = new combo_suggestion.ComboBoxSuggestion();
        txtTenSach = new com.raven.component.TextField();
        jLabel13 = new javax.swing.JLabel();
        txtTenNXB = new com.raven.component.TextField();
        jLabel14 = new javax.swing.JLabel();
        txtTenTacGia = new com.raven.component.TextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTenTheLoai = new com.raven.component.TextField();
        txtGiaNhap = new com.raven.component.TextField();
        jLabel17 = new javax.swing.JLabel();
        txtSoLuong = new com.raven.component.TextField();
        jLabel18 = new javax.swing.JLabel();
        btnThemSach = new com.raven.component.Button();
        txtNgayXB = new com.raven.component.TextField();
        jLabel19 = new javax.swing.JLabel();
        btnXoaSach = new com.raven.component.Button();
        panelShadow2 = new com.raven.swing.PanelShadow();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaPhieuNhap = new com.raven.component.TextField();
        jLabel9 = new javax.swing.JLabel();
        cboNhanVien = new combo_suggestion.ComboBoxSuggestion();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtDate1 = new com.raven.component.TextField();
        cboNhaCungCap = new combo_suggestion.ComboBoxSuggestion();
        jLabel11 = new javax.swing.JLabel();
        btnReset = new com.raven.component.Button();
        btnTaoPhieuNhap = new com.raven.component.Button();
        panelShadow3 = new com.raven.swing.PanelShadow();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachNhap = new com.raven.component.Table();
        btnLuuPhieu = new com.raven.component.Button();
        jLabel21 = new javax.swing.JLabel();
        txtTongCong = new com.raven.component.TextField();
        btnHuyPhieu = new com.raven.component.Button();

        dateChooser.setTextRefernce(txtDate1);

        setMaximumSize(new java.awt.Dimension(1041, 800));
        setMinimumSize(new java.awt.Dimension(1041, 800));
        setPreferredSize(new java.awt.Dimension(1041, 800));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("THÊM NHÀ CUNG CẤP");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 110, 207));
        jLabel3.setText("Thông tin sách");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Mã sách");

        cboMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaSachActionPerformed(evt);
            }
        });

        txtTenSach.setBackground(new java.awt.Color(235, 235, 235));
        txtTenSach.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Tên sách");

        txtTenNXB.setBackground(new java.awt.Color(235, 235, 235));
        txtTenNXB.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tên nhà xuất bản");

        txtTenTacGia.setBackground(new java.awt.Color(235, 235, 235));
        txtTenTacGia.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Tên tác giả");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tên thể loại");

        txtTenTheLoai.setBackground(new java.awt.Color(235, 235, 235));
        txtTenTheLoai.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Giá nhập");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Số lượng");

        btnThemSach.setBackground(new java.awt.Color(76, 175, 80));
        btnThemSach.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/addWhite.png"))); // NOI18N
        btnThemSach.setText("Thêm sách");
        btnThemSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemSach.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemSach.setIconTextGap(15);
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        txtNgayXB.setBackground(new java.awt.Color(235, 235, 235));
        txtNgayXB.setEnabled(false);
        txtNgayXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayXBActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Ngày xuất bản");

        btnXoaSach.setBackground(new java.awt.Color(244, 67, 54));
        btnXoaSach.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/trash.png"))); // NOI18N
        btnXoaSach.setText("Xóa");
        btnXoaSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaSach.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoaSach.setIconTextGap(15);
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayXB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap(716, Short.MAX_VALUE)
                .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtTenTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(txtNgayXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(140, 110, 207));
        jLabel7.setText("Thông tin phiếu nhập");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã phiếu nhập");

        txtMaPhieuNhap.setBackground(new java.awt.Color(235, 235, 235));
        txtMaPhieuNhap.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nhà cung cấp");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nhân viên nhập");

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày lập phiếu");

        btnReset.setBackground(new java.awt.Color(152, 116, 220));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Rotate.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReset.setIconTextGap(15);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTaoPhieuNhap.setBackground(new java.awt.Color(0, 140, 186));
        btnTaoPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/edit_1.png"))); // NOI18N
        btnTaoPhieuNhap.setText("Tạo phiếu nhập");
        btnTaoPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaoPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTaoPhieuNhap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTaoPhieuNhap.setIconTextGap(15);
        btnTaoPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow2Layout = new javax.swing.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShadow2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelShadow2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelShadow2Layout.createSequentialGroup()
                                .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(panelShadow2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cboNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShadow2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cboNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnTaoPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(140, 110, 207));
        jLabel20.setText("Bảng thông tin");
        jLabel20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        tblSachNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu nhập", "Mã sách", "Tên nhà xuất bản", "Tên thể loại", "Tên sách", "Tên tác giả", "Ngày xuất bản", "Giá nhập", "Số lượng nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSachNhap);

        javax.swing.GroupLayout panelShadow3Layout = new javax.swing.GroupLayout(panelShadow3);
        panelShadow3.setLayout(panelShadow3Layout);
        panelShadow3Layout.setHorizontalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow3Layout.setVerticalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnLuuPhieu.setBackground(new java.awt.Color(255, 128, 0));
        btnLuuPhieu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Tick Box.png"))); // NOI18N
        btnLuuPhieu.setText("Lưu phiếu");
        btnLuuPhieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLuuPhieu.setIconTextGap(15);
        btnLuuPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPhieuActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Tổng cộng: ");

        btnHuyPhieu.setBackground(new java.awt.Color(244, 67, 54));
        btnHuyPhieu.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cancel.png"))); // NOI18N
        btnHuyPhieu.setText("Hủy phiếu");
        btnHuyPhieu.setToolTipText("");
        btnHuyPhieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHuyPhieu.setIconTextGap(15);
        btnHuyPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyPhieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHuyPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuuPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelShadow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(383, 383, 383))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(panelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLuuPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHuyPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhieuNhapActionPerformed
        conn.open();
        LocalDate homNay = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String strDay = homNay.format(formatter);

        String sql = "SELECT COUNT(*) AS count FROM PHIEUNHAP WHERE NGAYNHAP = '" + strDay + "'";
        ResultSet rs = conn.executeQuery(sql);
        try {
            if (rs.next()) {
                int stt = rs.getInt("count");
                stt++;
                String strStt = String.format("%03d", stt);
                String strMa = "PN" + homNay.format(DateTimeFormatter.ofPattern("ddMMyyyy")) + strStt;
                txtMaPhieuNhap.setText(strMa);
                PhieuNhapDTO pn = new PhieuNhapDTO();
                pn.setMaPhieuNhap(strMa);
                LocalDate ngayNhapLocalDate = LocalDate.parse(strDay);
                Date ngayNhapDate = java.sql.Date.valueOf(ngayNhapLocalDate);
                pn.setNgayNhap(ngayNhapDate);
                NhanVienDTO nv = (NhanVienDTO) cboNhanVien.getSelectedItem();
                pn.setMaNV(nv.getMaNV());
                NhaCungCapDTO ncc = (NhaCungCapDTO) cboNhaCungCap.getSelectedItem();
                pn.setMaNCC(ncc.getMaNCC());
                pn.setThanhTien(0.0);
                boolean kq = PhieuNhapDAO.themPhieuNhap(pn);
                if(kq)
                {
                    JOptionPane.showMessageDialog(this, "Phiếu nhập được tạo thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    ArrayList<PhieuNhapDTO> ds = PhieuNhapDAO.layDS();
                    formPhieuNhap.updateTableData(ds);
                    
                }
                else
                    JOptionPane.showMessageDialog(this, "Tạo phiếu nhập thất bại thất bại.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
        } catch (SQLException ex) {
            Logger.getLogger(Form_ThemPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn.close();
    }//GEN-LAST:event_btnTaoPhieuNhapActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate1ActionPerformed

    private void cboMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaSachActionPerformed
        conn.open();
        SachDTO sach = (SachDTO) cboMaSach.getSelectedItem();
        String sql = "Select TENNXB,TENTL,TENSACH,TENTG,NGAYXUATBAN,GIABAN,SOLUONGTON from SACH,NHAXUATBAN,THELOAI,TACGIA where SACH.MANXB=NHAXUATBAN.MANXB and SACH.MATL=THELOAI.MATL and SACH.MATG=TACGIA.MATG and MASACH = '"+sach.getMaSach()+"' ORDER BY CAST(SUBSTRING(MASACH, 2, LEN(MASACH) - 1) AS INT)";
        ResultSet rs = conn.executeQuery(sql);
        try {
            while(rs.next()) {
                txtTenNXB.setText(rs.getString("TENNXB"));
                txtTenTheLoai.setText(rs.getString("TENTL"));
                txtTenSach.setText(rs.getString("TENSACH"));
                txtTenTacGia.setText(rs.getString("TENTG"));
                txtNgayXB.setText(rs.getDate("NGAYXUATBAN").toString());
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        conn.close();
    }//GEN-LAST:event_cboMaSachActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        conn.open();

        if(txtGiaNhap.getText().isEmpty()) {
            showMessage("Vui lòng nhập giá nhập!");
            conn.close();
            return;
        }

        Double giaNhap = null;
        try {
            giaNhap = Double.parseDouble(txtGiaNhap.getText());
        } catch (NumberFormatException e) {
            showMessage("Giá nhập phải là một số hợp lệ!");
            conn.close();
            return;
        }

        if(txtSoLuong.getText().isEmpty()) {
            showMessage("Vui lòng nhập số lượng!");
            conn.close();
            return;
        }

        int soLuong = 0;
        try {
            soLuong = Integer.parseInt(txtSoLuong.getText());
        } catch (NumberFormatException e) {
            showMessage("Số lượng phải là một số hợp lệ!");
            conn.close();
            return;
        }

        if(txtMaPhieuNhap.getText().isEmpty()) {
            showMessage("Vui lòng tạo phiếu nhập trước khi thêm sản phẩm!");
            conn.close();
            return;
        }

        Double tongtien = giaNhap * soLuong;
        ChiTietPhieuNhapDTO ctpn = new ChiTietPhieuNhapDTO();
        ctpn.setMaPhieuNhap(txtMaPhieuNhap.getText());
        SachDTO sach = (SachDTO) cboMaSach.getSelectedItem();
        if (sach == null) {
            showMessage("Vui lòng chọn sách hợp lệ!");
            conn.close();
            return;
        }
        ctpn.setMaSach(sach.getMaSach());
        ctpn.setGiaNhap(giaNhap);
        ctpn.setSoLuongNhap(soLuong);
        ctpn.setTongTien(tongtien);

        if (ChiTietPhieuNhapDAO.kiemTraTrungKhoaChinh(ctpn.getMaSach(), ctpn.getMaPhieuNhap())) {
            JOptionPane.showMessageDialog(this, "Sách đã tồn tại trong phiếu: " + ctpn.getMaSach() + ", " + ctpn.getMaPhieuNhap());
            conn.close();
            return;
        }

        boolean kq = ChiTietPhieuNhapDAO.themChiTietPN(ctpn);
        tongTienPN();
        String sql = "UPDATE SACH SET SOLUONGTON = SOLUONGTON + ? WHERE MASACH = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, soLuong);
            ps.setString(2, sach.getMaSach());
            ps.executeUpdate();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cập nhật số lượng sách: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            conn.close();
            return;
        }

        if (kq) {
            JOptionPane.showMessageDialog(this, "Sách đã được thêm thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            updateTableDataChiTietPN();
            updateTableDataPhieuNhap();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Sách thất bại.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        conn.close();
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        conn.open();
        int selectedRow = tblSachNhap.getSelectedRow();
        if(selectedRow != -1)
        {
            SachDTO sach = (SachDTO) cboMaSach.getSelectedItem();
            boolean kq = ChiTietPhieuNhapDAO.xoaChiTietPN(sach.getMaSach(), txtMaPhieuNhap.getText());
            if(kq)
            {
                JOptionPane.showMessageDialog(this, "Sách đã được hủy thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                tongTienPN();
                updateTableDataChiTietPN();
                updateTableDataPhieuNhap();
            }
        }
        else {
            showMessage("Vui lòng chọn dòng muốn xóa!");
        }
        conn.close();
    }//GEN-LAST:event_btnXoaSachActionPerformed

    private void btnHuyPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyPhieuActionPerformed
        MessageDialog obj = new MessageDialog(main);
        obj.showMessage("Bạn chắc chắn muốn hủy phiếu ?", "Tất cả dữ liệu đã nhập sẽ mất");
        if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            xoaPN();
            SwingUtilities.getWindowAncestor(this).dispose();
        } else {
            System.out.println("User clicked Cancel");
        }
    }//GEN-LAST:event_btnHuyPhieuActionPerformed

    private void btnLuuPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPhieuActionPerformed
        if(txtMaPhieuNhap.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Phiếu nhập chưa được tạo","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Phiếu nhập được lưu thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_btnLuuPhieuActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        if(showMessage("Tất cả dữ liệu đã nhập sẽ mất bạn muốn Reset chứ ?"))
        {
            xoaPN();
            model.setRowCount(0);
            txtMaPhieuNhap.setText("");
            txtTongCong.setText("");
            txtGiaNhap.setText("");
            txtSoLuong.setText("");
        }
        else{
            
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtNgayXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayXBActionPerformed
    
    public void xoaPN()
    {
        if(txtMaPhieuNhap.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Phiếu nhập đã được hủy thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        boolean kq = ChiTietPhieuNhapDAO.xoaChiTietPNTheoMa(txtMaPhieuNhap.getText());
        kq = PhieuNhapDAO.xoaPhieuNhap(txtMaPhieuNhap.getText());
        if(kq)
        {
            JOptionPane.showMessageDialog(this, "Phiếu nhập đã được hủy thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Hủy phiếu thất bại.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        updateTableDataPhieuNhap();
    }
    
    public void updateTableDataChiTietPN() {
        model = (DefaultTableModel) tblSachNhap.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trước khi cập nhật mới
        SachDTO sach = (SachDTO) cboMaSach.getSelectedItem();
        String sql = "Select MAPHIEUNHAP,CHITIETPN.MASACH,TENNXB,TENTL,TENSACH,TENTG,NGAYXUATBAN,GIANHAP,SOLUONGNHAP from SACH,NHAXUATBAN,THELOAI,TACGIA,CHITIETPN where SACH.MANXB=NHAXUATBAN.MANXB and SACH.MATL=THELOAI.MATL and SACH.MATG=TACGIA.MATG and SACH.MASACH=CHITIETPN.MASACH and MAPHIEUNHAP = '"+txtMaPhieuNhap.getText()+"'";
        conn.open();
        ResultSet rs = conn.executeQuery(sql);
        try {
            while(rs.next()) {
                String maPhieuNhap = rs.getString("MAPHIEUNHAP");
                String maSach = rs.getString("MASACH");
                String tenNXB = rs.getNString("TENNXB");
                String tenTL = rs.getNString("TENTL");
                String tenSach = rs.getNString("TENSACH");
                String tenTG = rs.getNString("TENTG");
                String ngayXB = rs.getDate("NGAYXUATBAN").toString();
                Double giaNhap1 = rs.getDouble("GIANHAP");
                int soLuongNhap = rs.getInt("SOLUONGNHAP");
                Object[] rowData = {maPhieuNhap, maSach,tenNXB, tenTL, tenSach, tenTG, ngayXB, giaNhap1,soLuongNhap};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void updateTableDataPhieuNhap()
    {
        ArrayList<PhieuNhapDTO> pn = PhieuNhapDAO.layDS();
        formPhieuNhap.updateTableData(pn);
    }
    
    private boolean showMessage(String message) {
    Frame parentFrame = getParentFrame(this);
    if (parentFrame != null) {
        Message obj = new Message(parentFrame, true);
        obj.showMessage(message);
        return obj.isOk();
    } else {
        return false;
    }
}

private Frame getParentFrame(Component component) {
    while (component != null) {
        if (component instanceof Frame) {
            return (Frame) component;
        }
        component = component.getParent();
    }
    return null;
}

    
    public void tongTienPN() {
        String sql = "SELECT SUM(TONGTIEN) AS tongTien FROM CHITIETPN WHERE MAPHIEUNHAP = ?";
        int thanhTien = 0;
        try (PreparedStatement statement = conn.prepareStatement(sql)) {
            statement.setString(1, txtMaPhieuNhap.getText());
            ResultSet rs = statement.executeQuery();

            if (rs.next()) {
                thanhTien = rs.getInt("tongTien");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        // Update THANHTIEN in PHIEUNHAP table
        sql = "UPDATE PHIEUNHAP SET THANHTIEN = ? WHERE MAPHIEUNHAP = ?";
        try (PreparedStatement statement = conn.prepareStatement(sql)) {
            statement.setInt(1, thanhTien);
            statement.setString(2, txtMaPhieuNhap.getText());
            statement.executeUpdate();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        txtTongCong.setText(String.valueOf(thanhTien));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnHuyPhieu;
    private com.raven.component.Button btnLuuPhieu;
    private com.raven.component.Button btnReset;
    private com.raven.component.Button btnTaoPhieuNhap;
    private com.raven.component.Button btnThemSach;
    private com.raven.component.Button btnXoaSach;
    private combo_suggestion.ComboBoxSuggestion cboMaSach;
    private combo_suggestion.ComboBoxSuggestion cboNhaCungCap;
    private combo_suggestion.ComboBoxSuggestion cboNhanVien;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelShadow panelShadow1;
    private com.raven.swing.PanelShadow panelShadow2;
    private com.raven.swing.PanelShadow panelShadow3;
    private com.raven.component.Table tblSachNhap;
    private com.raven.component.TextField txtDate1;
    private com.raven.component.TextField txtGiaNhap;
    private com.raven.component.TextField txtMaPhieuNhap;
    private com.raven.component.TextField txtNgayXB;
    private com.raven.component.TextField txtSoLuong;
    private com.raven.component.TextField txtTenNXB;
    private com.raven.component.TextField txtTenSach;
    private com.raven.component.TextField txtTenTacGia;
    private com.raven.component.TextField txtTenTheLoai;
    private com.raven.component.TextField txtTongCong;
    // End of variables declaration//GEN-END:variables
}
