/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import SQLServerProvider.SQLServerProvider;
import com.DTO.HoaDonDTO;
import com.DTO.NhaCungCapDTO;
import com.DTO.NhanVienDTO;
import com.java.loadHoaDon;
import com.java.loadNCC;
import com.java.loadNV;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER NITRO5
 */
public class Form_HoaDon extends javax.swing.JPanel {

    private Main main;
    SQLServerProvider conn = new SQLServerProvider();
    /**
     * Creates new form Form_HoaDon
     */
    public Form_HoaDon(Main main) {
        this.main = main;
        initComponents();
        conn.open();
        tblGioHang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                displaySelectedRow();
            }
        }});
        loadCboHD();
        conn.close();
    }
    public void displaySelectedRow() {
        int selectedRow = tblGioHang.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy giá trị từ các cột của dòng được chọn
            String maHD = (String) tblGioHang.getValueAt(selectedRow, 0);
            String maSach = (String) tblGioHang.getValueAt(selectedRow, 1);
            String tenSach = (String) tblGioHang.getValueAt(selectedRow, 2);
            String ngayMua = (String) tblGioHang.getValueAt(selectedRow, 3);
            int soLuong = Integer.parseInt(tblGioHang.getValueAt(selectedRow, 4).toString());
            int tongTien = Integer.parseInt(tblGioHang.getValueAt(selectedRow, 5).toString());

            // Hiển thị hoặc xử lý giá trị của dòng được chọn
            txtMaHD.setText(maHD);
            txtNgayLap.setText(ngayMua);
            txtMaSach.setText(maSach);
            txtDonGia3.setText(tenSach);
            txtTacGia5.setText(String.valueOf(soLuong));
            txtTheLoai3.setText(String.valueOf(tongTien));
            
        }
    }
    public void loadCboHD()
    {
        loadHoaDon load = new loadHoaDon();
        List<HoaDonDTO> list = load.getData();
        cboMaHD.removeAllItems();
        
        List<String> maHDList = new ArrayList<>();
        for (HoaDonDTO hd : list) {
            maHDList.add(hd.getMaHD());
        }
        
        maHDList.forEach(o -> {
            cboMaHD.addItem(o);
        }); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboMaHD = new combo_suggestion.ComboBoxSuggestion();
        btnTraCuu = new com.raven.component.Button();
        panelShadow6 = new com.raven.swing.PanelShadow();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtDonGia3 = new com.raven.component.TextField();
        jLabel40 = new javax.swing.JLabel();
        txtMaSach = new com.raven.component.TextField();
        jLabel42 = new javax.swing.JLabel();
        txtMaHD = new com.raven.component.TextField();
        jLabel43 = new javax.swing.JLabel();
        txtTheLoai3 = new com.raven.component.TextField();
        txtNgayLap = new com.raven.component.TextField();
        txtTacGia5 = new com.raven.component.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new com.raven.component.Table();

        setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã hóa đơn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CHI TIẾT HÓA ĐƠN");

        cboMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaHDActionPerformed(evt);
            }
        });

        btnTraCuu.setBackground(new java.awt.Color(153, 153, 255));
        btnTraCuu.setForeground(new java.awt.Color(255, 255, 255));
        btnTraCuu.setText("Tra Cứu");
        btnTraCuu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuuActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(140, 110, 207));
        jLabel36.setText("Thông tin hóa đơn");
        jLabel36.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Mã hóa đơn");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Mã sách");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Ngày lập");

        txtDonGia3.setBackground(new java.awt.Color(235, 235, 235));
        txtDonGia3.setEnabled(false);
        txtDonGia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGia3ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("Tên sách");

        txtMaSach.setBackground(new java.awt.Color(235, 235, 235));
        txtMaSach.setEnabled(false);
        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setText("Số lượng");

        txtMaHD.setBackground(new java.awt.Color(235, 235, 235));
        txtMaHD.setEnabled(false);
        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setText("Tổng tiền");

        txtTheLoai3.setBackground(new java.awt.Color(235, 235, 235));
        txtTheLoai3.setEnabled(false);
        txtTheLoai3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTheLoai3ActionPerformed(evt);
            }
        });

        txtNgayLap.setBackground(new java.awt.Color(235, 235, 235));
        txtNgayLap.setEnabled(false);
        txtNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLapActionPerformed(evt);
            }
        });

        txtTacGia5.setBackground(new java.awt.Color(235, 235, 235));
        txtTacGia5.setEnabled(false);
        txtTacGia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGia5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow6Layout = new javax.swing.GroupLayout(panelShadow6);
        panelShadow6.setLayout(panelShadow6Layout);
        panelShadow6Layout.setHorizontalGroup(
            panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow6Layout.createSequentialGroup()
                .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelShadow6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelShadow6Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(39, 39, 39)
                                .addComponent(txtNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelShadow6Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel38))
                        .addGap(22, 22, 22)
                        .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDonGia3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelShadow6Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(txtTacGia5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelShadow6Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(18, 18, 18)
                                .addComponent(txtTheLoai3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 167, Short.MAX_VALUE))
        );
        panelShadow6Layout.setVerticalGroup(
            panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow6Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShadow6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel43)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTheLoai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(panelShadow6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)
                            .addComponent(txtTacGia5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã sách", "Tên sách", "Ngày mua", "Số lượng", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblGioHangPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblGioHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cboMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(577, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(392, 392, 392))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(panelShadow6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShadow6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaHDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMaHDActionPerformed

    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
      
        conn.open();
        System.out.println("s");
        String hd = (String) cboMaHD.getSelectedItem();
        System.out.println(hd);
        String sql = "Select CHITIETHD.MAHD, SACH.MASACH, TENSACH, NGAYLAP, SOLUONG, TONGTIEN from HOADON, CHITIETHD, SACH WHERE HOADON.MAHD = CHITIETHD.MAHD AND CHITIETHD.MASACH = SACH.MASACH AND CHITIETHD.MAHD = '"+hd+"'";
        ResultSet rs = conn.executeQuery(sql);
        DefaultTableModel model = (DefaultTableModel) this.tblGioHang.getModel();
        model.setRowCount(0); // Xóa tất cả các dòng
        try {
            while(rs.next()) {
                String maHD = String.valueOf(rs.getString("MAHD"));
                String maSach = String.valueOf(rs.getString("MASACH"));
                String tenSach = String.valueOf(rs.getString("TENSACH"));
                String ngayLap = String.valueOf(rs.getDate("NGAYLAP"));
                int soLuong = rs.getInt("SOLUONG");
                int tongTien = rs.getInt("TONGTIEN");
                Object[] rowData = {maHD,maSach,tenSach,ngayLap,soLuong,tongTien};
                    model.addRow(rowData);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        conn.close();
    }//GEN-LAST:event_btnTraCuuActionPerformed

    private void txtDonGia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGia3ActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void txtTheLoai3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTheLoai3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTheLoai3ActionPerformed

    private void txtNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayLapActionPerformed

    private void txtTacGia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGia5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGia5ActionPerformed

    private void tblGioHangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblGioHangPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGioHangPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnTraCuu;
    private combo_suggestion.ComboBoxSuggestion cboMaHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelShadow panelShadow6;
    private com.raven.component.Table tblGioHang;
    private com.raven.component.TextField txtDonGia3;
    private com.raven.component.TextField txtMaHD;
    private com.raven.component.TextField txtMaSach;
    private com.raven.component.TextField txtNgayLap;
    private com.raven.component.TextField txtTacGia5;
    private com.raven.component.TextField txtTheLoai3;
    // End of variables declaration//GEN-END:variables
}
