/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.DAO.SachDAO;
import com.DTO.NhaXuatBanDTO;
import com.DTO.SachDTO;
import com.DTO.TacGiaDTO;
import com.DTO.TheLoaiDTO;
import com.java.loadNXB;
import com.java.loadTG;
import com.java.loaiTL;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class Form_SuaSach extends javax.swing.JPanel {
    private Form_QuanLySach formQuanLySach;
    String duongDanAnh = "";
    
    /**
     * Creates new form Form_SuaSach
     */
    
    public Form_SuaSach(Form_QuanLySach fromQuanLySach, String maSach,String anhSach, String tenSach,String tenTL, String tenTG, String ngayXB, String tenNXB, String giaBan, String soLuongTon) {
        initComponents();
        loadCbo();
        this.formQuanLySach = fromQuanLySach;
        txtMaSach.setText(maSach);
        duongDanAnh = anhSach;
        lblAnh.setSize(194, 249);
        lblAnh.setIcon(ResizeImage(String.valueOf(duongDanAnh)));
        for (int i = 0; i < cboNXB.getItemCount(); i++) {
            NhaXuatBanDTO nhaXuatBan = (NhaXuatBanDTO) cboNXB.getItemAt(i);
            if (nhaXuatBan.getTenNXB().equals(tenNXB)) {
                cboNXB.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < cboTheLoai.getItemCount(); i++) {
            TheLoaiDTO theLoai = (TheLoaiDTO) cboTheLoai.getItemAt(i);
            if (theLoai.getTenTL().equals(tenTL)) {
                cboTheLoai.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < cboTacGia.getItemCount(); i++) {
            TacGiaDTO tacGia = (TacGiaDTO) cboTacGia.getItemAt(i);
            if (tacGia.getTenTG().equals(tenTG)) {
                cboTacGia.setSelectedIndex(i);
                break;
            }
        }
        txtTenSach.setText(tenSach);
        txtNgayXB.setText(ngayXB);
        txtGiaBan.setText(giaBan);
        txtSoLuong.setText(soLuongTon);
        System.out.println(duongDanAnh);
        
    }

    private void loadCbo()
    {
        loadCboNXB();
        loadCboTG();
        loadCboTL();
    }
    private void loadCboNXB()
    {  
        loadNXB load = new loadNXB();
        List<NhaXuatBanDTO> list = load.getData();
        cboNXB.removeAllItems();
        list.forEach(o -> {
            cboNXB.addItem(o);
        });
    }
    
    private void loadCboTG()
    {  
        loadTG load = new loadTG();
        List<TacGiaDTO> list = load.getData();
        cboTacGia.removeAllItems();
        list.forEach(o -> {
            cboTacGia.addItem(o);
        });
    }
    
    private void loadCboTL()
    {
        loaiTL load = new loaiTL();
        List<TheLoaiDTO> list = load.getData();
        cboTheLoai.removeAllItems();
        list.forEach(o -> {
            cboTheLoai.addItem(o);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaSach = new textfield.TextField();
        jLabel2 = new javax.swing.JLabel();
        cboTheLoai = new combobox.Combobox<>();
        btnHuy = new com.raven.component.Button();
        txtGiaBan = new textfield.TextField();
        cboTacGia = new combobox.Combobox<>();
        txtTenSach = new textfield.TextField();
        cboNXB = new combobox.Combobox<>();
        txtNgayXB = new textfield.TextField();
        txtSoLuong = new textfield.TextField();
        btnCapNhat = new com.raven.component.Button();
        btnThemNXB = new com.raven.component.Button();
        btnThemTL = new com.raven.component.Button();
        btnThemTG = new com.raven.component.Button();
        lblAnh = new javax.swing.JLabel();
        btnThemAnh = new com.raven.component.Button();

        txtMaSach.setEnabled(false);
        txtMaSach.setLabelText("Nhập mã sách");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("CẬP NHẬT THÔNG TIN SÁCH");

        cboTheLoai.setLabeText("Chọn thể loại");

        btnHuy.setBackground(new java.awt.Color(244, 67, 54));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cancel.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setIconTextGap(15);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtGiaBan.setLabelText("Nhập giá bán");

        cboTacGia.setLabeText("Chọn tác giả");

        txtTenSach.setLabelText("Nhập tên sách");

        cboNXB.setLabeText("Chọn nhà xuất bản");

        txtNgayXB.setLabelText("Nhập ngày xuất bản");

        txtSoLuong.setEnabled(false);
        txtSoLuong.setLabelText("Nhập số lượng");

        btnCapNhat.setBackground(new java.awt.Color(0, 140, 186));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/PenToSquare.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCapNhat.setIconTextGap(15);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThemNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add.png"))); // NOI18N
        btnThemNXB.setShadowColor(new java.awt.Color(102, 102, 255));

        btnThemTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add.png"))); // NOI18N
        btnThemTL.setShadowColor(new java.awt.Color(102, 102, 255));

        btnThemTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add.png"))); // NOI18N
        btnThemTG.setShadowColor(new java.awt.Color(102, 102, 255));

        lblAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Book.png"))); // NOI18N
        lblAnh.setToolTipText("");
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        btnThemAnh.setBackground(new java.awt.Color(102, 153, 255));
        btnThemAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/addWhite.png"))); // NOI18N
        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemAnh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemAnh.setIconTextGap(15);
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(193, 193, 193))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNgayXB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThemTG, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboNXB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemTL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnThemNXB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNgayXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnThemTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnThemTG, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed

    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int selectedRow = formQuanLySach.getSelectedRowIndex();
        if (selectedRow != -1) {
            if (txtMaSach.getText().isEmpty() || txtTenSach.getText().isEmpty() || txtGiaBan.getText().isEmpty() || txtSoLuong.getText().isEmpty() || txtNgayXB.getText().isEmpty() || cboNXB.getSelectedItem() == null || cboTacGia.getSelectedItem() == null || cboTheLoai.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin sách.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                Double.parseDouble(txtGiaBan.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Giá bán phải là một số.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                Integer.parseInt(txtSoLuong.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số lượng tồn phải là một số nguyên.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
        
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date ngayXuatBan = null;
            try {
                ngayXuatBan = dateFormat.parse(txtNgayXB.getText());
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Định dạng ngày không hợp lệ. Vui lòng nhập theo định dạng dd/MM/yyyy.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
        
            SachDTO s = new SachDTO();
            s.setMaSach(txtMaSach.getText());
            s.setTenSach(txtTenSach.getText());
            NhaXuatBanDTO nxb = (NhaXuatBanDTO) cboNXB.getSelectedItem();
            s.setMaNXB(nxb.getMaNXB());
            s.setGiaBan(Double.parseDouble(txtGiaBan.getText().toString()));
            TacGiaDTO tg = (TacGiaDTO) cboTacGia.getSelectedItem();
            s.setMaTG(tg.getMaTG());
            TheLoaiDTO tl = (TheLoaiDTO) cboTheLoai.getSelectedItem();
            s.setMaTL(tl.getMaTL());
            s.setSoLuongTon(Integer.parseInt(txtSoLuong.getText()));
            s.setNgayXuatBan(ngayXuatBan);
            s.setAnhSach(duongDanAnh);
            boolean kq = SachDAO.capNhatSach(s);
            if(kq)
            {
                JOptionPane.showMessageDialog(this, "Sách đã được cập nhật thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ArrayList<SachDTO> ds = SachDAO.layDS();
                formQuanLySach.capNhatDuLieuBang(ds);
                SwingUtilities.getWindowAncestor(this).dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn cập nhật.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        try {
            JFileChooser f = new JFileChooser("D:\\QuanLyNhaSach\\src\\img");
            f.setDialogTitle("Mở File");
            f.showOpenDialog(null);
            File ftenAnh = f.getSelectedFile();
            duongDanAnh = ftenAnh.getAbsolutePath();
            if(duongDanAnh != null)
            {
                lblAnh.setIcon(ResizeImage(String.valueOf(duongDanAnh)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chưa chọn ảnh");
        }

    }//GEN-LAST:event_btnThemAnhActionPerformed

    private Icon ResizeImage(String imagePath) {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnCapNhat;
    private com.raven.component.Button btnHuy;
    private com.raven.component.Button btnThemAnh;
    private com.raven.component.Button btnThemNXB;
    private com.raven.component.Button btnThemTG;
    private com.raven.component.Button btnThemTL;
    private combobox.Combobox<Object> cboNXB;
    private combobox.Combobox<Object> cboTacGia;
    private combobox.Combobox<Object> cboTheLoai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnh;
    private textfield.TextField txtGiaBan;
    private textfield.TextField txtMaSach;
    private textfield.TextField txtNgayXB;
    private textfield.TextField txtSoLuong;
    private textfield.TextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
