/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import SQLServerProvider.SQLServerProvider;
import com.DAO.NhanVienDAO;
import com.DAO.TaiKhoanDAO;
import com.DTO.NhanVienDTO;
import com.DTO.TaiKhoanDTO;
import com.java.loadNV;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javaswingdev.message.MessageDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
    
/**
 *
 * @author ACER
 */
public class Form_ThemTaiKhoan extends javax.swing.JPanel {
    private Form_QuanLyTaiKhoan formQuanLytaiKhoan;
    private Main main;
    SQLServerProvider conn = new SQLServerProvider();
    /**
     * Creates new form Form_ThemTaiKhoan
     */
    public Form_ThemTaiKhoan(Form_QuanLyTaiKhoan formQuanLytaiKhoan,Main main) {
        this.formQuanLytaiKhoan = formQuanLytaiKhoan;
        this.main = main;
        initComponents();
        conn.open();
        loadCboNV();
        
        conn.close();
    }
     private void loadCboNV() {  
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        List<NhanVienDTO> allNhanVien = nhanVienDAO.layDS();
        List<TaiKhoanDTO> allTaiKhoan = TaiKhoanDAO.layDS();

        List<String> maNVsWithAccount = allTaiKhoan.stream()
                                                   .map(TaiKhoanDTO::getMaNV)
                                                   .collect(Collectors.toList());

        List<NhanVienDTO> nhanVienWithoutAccount = allNhanVien.stream()
                                                              .filter(nv -> !maNVsWithAccount.contains(nv.getMaNV()))
                                                              .collect(Collectors.toList());

        cboNhanVien.removeAllItems();
        nhanVienWithoutAccount.forEach(nv -> {
            cboNhanVien.addItem(nv);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnHuy = new com.raven.component.Button();
        btnThemTK = new com.raven.component.Button();
        txtTenHT = new textfield.TextField();
        txtTenDN = new textfield.TextField();
        txtMatKhau = new com.raven.swing.PasswordField();
        cboNhanVien = new combo_suggestion.ComboBoxSuggestion();
        cboPhanQuyen = new combo_suggestion.ComboBoxSuggestion();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("THÊM TÀI KHOẢN");

        btnHuy.setBackground(new java.awt.Color(244, 67, 54));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cancel.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setIconTextGap(15);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThemTK.setBackground(new java.awt.Color(76, 175, 80));
        btnThemTK.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/addWhite.png"))); // NOI18N
        btnThemTK.setText("Thêm tài khoản");
        btnThemTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemTK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemTK.setIconTextGap(15);
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        txtTenHT.setLabelText("Nhập tên hiển thị");

        txtTenDN.setLabelText("Nhập tên đăng nhập");

        txtMatKhau.setLabelText("Nhập mật khẩu");
        txtMatKhau.setName("Nhập mật khẩu"); // NOI18N

        cboPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenHT, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(cboNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboPhanQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtTenDN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed

        MessageDialog obj = new MessageDialog(main);

        obj.showMessage("Bạn chắc chắn muốn thoát ?", "Tất cả dữ liệu đã nhập sẽ mất");
        if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            SwingUtilities.getWindowAncestor(this).dispose();
        } else {
            System.out.println("User clicked Cancel");
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        String tenDN = txtTenDN.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        String tenHT = txtTenHT.getText();
        String phanQuyen = (String) cboPhanQuyen.getSelectedItem();
        NhanVienDTO nv = (NhanVienDTO) cboNhanVien.getSelectedItem();
        String maNV = nv.getMaNV();
        if (tenDN.isEmpty() || matKhau.isEmpty() || tenHT.isEmpty() || phanQuyen == null || maNV == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        TaiKhoanDTO taiKhoan = new TaiKhoanDTO();
        taiKhoan.setTenDN(tenDN);
        taiKhoan.setTenHT(tenHT);
        taiKhoan.setMatKhau(matKhau);
        taiKhoan.setPhanQuyen(phanQuyen);
        taiKhoan.setMaNV(maNV);

        boolean kq = TaiKhoanDAO.themTaiKhoan(taiKhoan);
        if (kq) {
            JOptionPane.showMessageDialog(this, "Tài khoản đã được thêm thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ArrayList<TaiKhoanDTO> ds = TaiKhoanDAO.layDS();
            formQuanLytaiKhoan.capNhatDuLieuBang(ds);
        } else {
            JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnThemTKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnHuy;
    private com.raven.component.Button btnThemTK;
    private combo_suggestion.ComboBoxSuggestion cboNhanVien;
    private combo_suggestion.ComboBoxSuggestion cboPhanQuyen;
    private javax.swing.JLabel jLabel2;
    private com.raven.swing.PasswordField txtMatKhau;
    private textfield.TextField txtTenDN;
    private textfield.TextField txtTenHT;
    // End of variables declaration//GEN-END:variables
}
