/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.DAO.NhanVienDAO;
import com.DTO.ChucVuDTO;
import com.DTO.NhanVienDTO;
import com.java.loadChucVu;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class Form_SuaNhanVien extends javax.swing.JPanel {
    private Form_QuanLyNhanVien formQuanLyNhanVien;
    String duongDanAnh = "";
    /**
     * Creates new form Form_SuaNhanVien
     */
    public Form_SuaNhanVien(Form_QuanLyNhanVien formQuanLyNhanVien, String maNV, String anhNV, String tenNV, String tenCV, String diaChi, String soDT, String email) {
        initComponents();
        this.formQuanLyNhanVien = formQuanLyNhanVien;
        loadCboCV();
        for (int i = 0; i < cboChucVu.getItemCount(); i++) {
            ChucVuDTO nhaXuatBan = (ChucVuDTO) cboChucVu.getItemAt(i);
            if (nhaXuatBan.getTenCV().equals(tenCV)) {
                cboChucVu.setSelectedIndex(i);
                break;
            }
        }
        txtDiaChiNV.setText(diaChi);
        txtEmail.setText(email);
        txtMaNV.setText(maNV);
        txtSoDT.setText(soDT);
        txtTenNV.setText(tenNV);
        duongDanAnh = anhNV;
        lblAnh.setSize(174, 194);
        lblAnh.setIcon(ResizeImage(String.valueOf(duongDanAnh)));
    }

    private void loadCboCV()
    {  
        loadChucVu load = new loadChucVu();
        List<ChucVuDTO> list = load.getData();
        cboChucVu.removeAllItems();
        list.forEach(o -> {
            cboChucVu.addItem(o);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        btnThemAnh = new com.raven.component.Button();
        txtSoDT = new textfield.TextField();
        txtEmail = new textfield.TextField();
        cboChucVu = new combobox.Combobox<>();
        txtMaNV = new textfield.TextField();
        txtTenNV = new textfield.TextField();
        txtDiaChiNV = new textfield.TextField();
        btnThemChucVu = new com.raven.component.Button();
        btnCapNhat = new com.raven.component.Button();
        btnHuy = new com.raven.component.Button();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("SỬA THÔNG TIN NHÂN VIÊN");

        lblAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Customer.png"))); // NOI18N
        lblAnh.setToolTipText("");
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        btnThemAnh.setBackground(new java.awt.Color(102, 153, 255));
        btnThemAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/addWhite.png"))); // NOI18N
        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemAnh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemAnh.setIconTextGap(15);
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });

        txtSoDT.setLabelText("Nhập số điện thoại");

        txtEmail.setLabelText("Nhập Email");

        cboChucVu.setLabeText("Chọn chức vụ");

        txtMaNV.setEnabled(false);
        txtMaNV.setLabelText("Nhập mã nhân viên");

        txtTenNV.setLabelText("Nhập tên nhân viên");

        txtDiaChiNV.setLabelText("Nhập địa chỉ");

        btnThemChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add.png"))); // NOI18N
        btnThemChucVu.setShadowColor(new java.awt.Color(102, 102, 255));

        btnCapNhat.setBackground(new java.awt.Color(0, 140, 186));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/PenToSquare.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCapNhat.setIconTextGap(15);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(244, 67, 54));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cancel.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setIconTextGap(15);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtDiaChiNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThemChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThemChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        try {
            JFileChooser f = new JFileChooser("D:\\QuanLyNhaSach\\src\\img");
            f.setDialogTitle("Mở File");
            f.showOpenDialog(null);
            File ftenAnh = f.getSelectedFile();
            duongDanAnh = ftenAnh.getAbsolutePath();
            if(duongDanAnh != null)
            {
                lblAnh.setIcon(ResizeImage(String.valueOf(duongDanAnh)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chưa chọn ảnh");
        }
    }//GEN-LAST:event_btnThemAnhActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (txtMaNV.getText().isEmpty() || txtTenNV.getText().isEmpty() || txtSoDT.getText().isEmpty() || txtEmail.getText().isEmpty() || txtDiaChiNV.getText().isEmpty() || cboChucVu.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin sách.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String email = txtEmail.getText();
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ email hợp lệ.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }


        // Tiến hành thêm sách vào cơ sở dữ liệu với các thông tin đã kiểm tra
        NhanVienDTO nv = new NhanVienDTO();
        nv.setMaNV(txtMaNV.getText());
        nv.setHoTenNV(txtTenNV.getText());
        nv.setDiaChiNV(txtDiaChiNV.getText());
        nv.setEmailNV(txtEmail.getText());
        nv.setSoDT(txtSoDT.getText());
        ChucVuDTO cv = (ChucVuDTO) cboChucVu.getSelectedItem();
        nv.setMaCV(cv.getMaCV());
        nv.setAnhNV(duongDanAnh);
        nv.setTrangThai(1);
        boolean kq = NhanVienDAO.capNhatNhanVien(nv);
        if(kq)
        {
            JOptionPane.showMessageDialog(this, "Nhân viên đã được cập nhật thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ArrayList<NhanVienDTO> ds = NhanVienDAO.layDS();
            formQuanLyNhanVien.capNhatDuLieuBang(ds);
            //            SwingUtilities.getWindowAncestor(this).dispose();
        }
        else
        JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại.", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnHuyActionPerformed
    
    private Icon ResizeImage(String imagePath) {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    private boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email.matches(emailRegex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnCapNhat;
    private com.raven.component.Button btnHuy;
    private com.raven.component.Button btnThemAnh;
    private com.raven.component.Button btnThemChucVu;
    private combobox.Combobox<Object> cboChucVu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnh;
    private textfield.TextField txtDiaChiNV;
    private textfield.TextField txtEmail;
    private textfield.TextField txtMaNV;
    private textfield.TextField txtSoDT;
    private textfield.TextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
