/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.DAO.NhanVienDAO;
import com.DAO.TaiKhoanDAO;
import com.DTO.NhanVienDTO;
import com.DTO.TaiKhoanDTO;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class Form_SuaTaiKhoan extends javax.swing.JPanel {
    Form_QuanLyTaiKhoan formQuanLyTaiKhoan;
    /**
     * Creates new form Form_SuaTaiKhoan
     */
    public Form_SuaTaiKhoan(Form_QuanLyTaiKhoan formQuanLyTaiKhoan, String maNV, String tenHT, String tenDN, String matKhau, String tenNV, String email, String phanQuyen) {
        initComponents();
        loadCboNV();
        loadCboPhanQuyen();
        this.formQuanLyTaiKhoan = formQuanLyTaiKhoan;
        txtMatKhau.setText(matKhau);
        cboPhanQuyen.setSelectedItem(phanQuyen);
        txtTenDN.setText(tenDN);
        txtTenHT.setText(tenHT);
        selectNhanVien(tenNV);
    }
    
    private void loadCboPhanQuyen() {
        cboPhanQuyen.removeAllItems();
        // Assuming roles are defined in an array or can be fetched from a data source
        String[] roles = {"Admin", "User"}; 
        for (String role : roles) {
            cboPhanQuyen.addItem(role);
        }
    }
    private void selectNhanVien(String tenNV) {
        for (int i = 0; i < cboNhanVien.getItemCount(); i++) {
            NhanVienDTO nhanVien = (NhanVienDTO) cboNhanVien.getItemAt(i);
            if (nhanVien.getHoTenNV().equals(tenNV)) {
                cboNhanVien.setSelectedIndex(i);
                break;
            }
        }
    }
    private void loadCboNV() {  
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        List<NhanVienDTO> allNhanVien = nhanVienDAO.layDS();
        List<TaiKhoanDTO> allTaiKhoan = TaiKhoanDAO.layDS();

        List<String> maNVsWithAccount = allTaiKhoan.stream()
                                                   .map(TaiKhoanDTO::getMaNV)
                                                   .collect(Collectors.toList());

        List<NhanVienDTO> nhanVienWithoutAccount = allNhanVien.stream()
                                                              .filter(nv -> !maNVsWithAccount.contains(nv.getMaNV()))
                                                              .collect(Collectors.toList());

        cboNhanVien.removeAllItems();
        nhanVienWithoutAccount.forEach(nv -> {
            cboNhanVien.addItem(nv);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtTenHT = new textfield.TextField();
        txtTenDN = new textfield.TextField();
        txtMatKhau = new com.raven.swing.PasswordField();
        cboNhanVien = new combo_suggestion.ComboBoxSuggestion();
        cboPhanQuyen = new combo_suggestion.ComboBoxSuggestion();
        btnCapNhat = new com.raven.component.Button();
        btnHuy = new com.raven.component.Button();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel2.setText("SỬA TÀI KHOẢN");

        txtTenHT.setLabelText("Nhập tên hiển thị");

        txtTenDN.setEnabled(false);
        txtTenDN.setLabelText("Nhập tên đăng nhập");

        txtMatKhau.setLabelText("Nhập mật khẩu");
        txtMatKhau.setName("Nhập mật khẩu"); // NOI18N

        cboPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));

        btnCapNhat.setBackground(new java.awt.Color(0, 140, 186));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/PenToSquare.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCapNhat.setIconTextGap(15);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(244, 67, 54));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cancel.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setIconTextGap(15);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenHT, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(cboNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboPhanQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtTenDN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int selectedRow = formQuanLyTaiKhoan.getSelectedRowIndex();
        if (selectedRow != -1) {
            if (txtTenHT.getText().isEmpty() || txtTenDN.getText().isEmpty() || txtMatKhau.getText().isEmpty() || cboPhanQuyen.getSelectedItem() == null || cboNhanVien.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin tài khoản.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            TaiKhoanDTO taiKhoan = new TaiKhoanDTO();
            taiKhoan.setTenHT(txtTenHT.getText());
            taiKhoan.setTenDN(txtTenDN.getText());
            taiKhoan.setMatKhau(txtMatKhau.getText());
            taiKhoan.setPhanQuyen(cboPhanQuyen.getSelectedItem().toString());
            NhanVienDTO nhanVien = (NhanVienDTO) cboNhanVien.getSelectedItem();
            taiKhoan.setMaNV(nhanVien.getMaNV());

            boolean kq = TaiKhoanDAO.capNhatTaiKhoan(taiKhoan);
            if (kq) {
                JOptionPane.showMessageDialog(this, "Tài khoản đã được cập nhật thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ArrayList<TaiKhoanDTO> ds = TaiKhoanDAO.layDS();
                formQuanLyTaiKhoan.capNhatDuLieuBang(ds);
                SwingUtilities.getWindowAncestor(this).dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn cập nhật.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
         SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Button btnCapNhat;
    private com.raven.component.Button btnHuy;
    private combo_suggestion.ComboBoxSuggestion cboNhanVien;
    private combo_suggestion.ComboBoxSuggestion cboPhanQuyen;
    private javax.swing.JLabel jLabel2;
    private com.raven.swing.PasswordField txtMatKhau;
    private textfield.TextField txtTenDN;
    private textfield.TextField txtTenHT;
    // End of variables declaration//GEN-END:variables
}
